package uz.company.lunchbot.enums;

public enum AuditAction {
    USER_REGISTERED,
    USER_APPROVED,
    USER_REJECTED,
    USER_BLOCKED,
    USER_ROLE_CHANGED,
    MENU_ITEM_CREATED,
    MENU_ITEM_UPDATED,
    MENU_ITEM_ACTIVATED,
    MENU_ITEM_DEACTIVATED,
    SESSION_OPENED,
    SESSION_CLOSED,
    SESSION_CONFIRMED,
    SESSION_CANCELLED,
    SESSION_EXTENDED,
    ORDER_CREATED,
    ORDER_UPDATED,
    ORDER_SKIPPED,
    ORDER_CANCELLED,
    DELIVERY_CHANGED,
    CONTAINER_CHANGED,
    CALCULATION_REBUILT
}
